country = Country.find_by(country_code: 'AT') ? Country.find_by(country_code: 'AT') : Country.create(name:'Austria', country_code:'AT')
page = RidersPage.new(
Page:"Fahrer",
contet_block_1_headline:"Entscheide dich für die Besten",
content_block_1_paragraph:"Mit ofo nimmst du dir ein Fahrrad, kommst entspannt an und stellst es einfach wieder ab. Keine fixen Stationen, keine zusätzlichen Wege zu Fuß. So geht Bikesharing richtig.",
content_block_2_headline:"Leih/Schnapp dir ein Fahrrad von überall. Parke das Fahrrad überall.",
content_block_2_paragraph:"Mit stationslosem Bikesharing kannst du fahren, wo auch immer du hin möchtest. Alles was du danach tun musst, ist das Fahrrad wieder legal zu parken.",
call_to_action_1_headline:"Gleich heute losfahren!",
call_to_action_1_button_text:"Download",
content_block_3_headline:"ofo fahren ist ganz einfach",
content_block_3_paragraph:"Finden. Scannen. Fahren. Abschließen.",
how_to_step_1_headline:"Finde ein Fahrrad.",
how_to_step_1_paragraph:"Öffne die App und finde alle Fahrräder in deiner Nähe.",
how_to_step_2_headline:"Tippen und Scannen",
how_to_step_2_paragraph:"Tippe den "Entsperren" Button und scanne den Barcode direkt vom Fahrrad ein. Das Schloss entsperrt sich automatisch.",
how_to_step_3_headline:"Genieße die Fahrt",
how_to_step_3_paragraph:"Entdecke deine Stadt und komm sicher am Ziel an.",
how_to_step_4_headline:"Parken und abschließen",
how_to_step_4_paragraph:"Angekommen am Ziel, parke einfach dein Fahrrad sicher und legal, sowie schließe es manuell ab. Deine Fahrt endet automatisch.",
content_block_4_headline:"Der Beste Deal der Stadt",
content_block_4_paragraph:"Nur 50 Cent/30 Minuten",
content_block_5_headline:"Mit uns bist du sicher unterwegs",
bike_description_handle_bar:"Einzigartige Fahrrad-Identifikationsnummer",
bike_description_front_wheel:"LED Dynamo Vorderlicht - sichtbar bis 150m",
bike_description_title:"Robuste Reifen, pannensicher",
bike_description_frame_bar:"Starker aber leichter Aluminiumrahmen",
bike_description_seat:"Höhenverstellbarer Sattel",
bike_description_lock:"Smartes Fahrradschloss mit GPS Signal und mobiler Synchronisation. ",
bike_description_brake:"Verlässliche Bremsen",
bike_description_back_wheel:"Gut sichtbares, rotes Rücklicht um Fußgänger und Kraftfahrer aufmerksam zu machen",
bike_description_kcikstand:"Fahrradständer für aufrechtes Parken ohne fixe Station",
content_block_6_headline:"Gesehen in",
call_to_action_2_button_text:"Gleich heute losfahren!",
:"Download",
country: country
)
page.save
