country = Country.find_by(country_code: 'AT') ? Country.find_by(country_code: 'AT') : Country.create(name:'Austria ', country_code:'AT')
page = RidersPage.new(
Page:"",
contet_block_1_headline:"",
content_block_1_paragraph:"",
content_block_2_headline:"",
content_block_2_paragraph:"",
call_to_action_1_headline:"",
call_to_action_1_button_text:"",
content_block_3_headline:"",
content_block_3_paragraph:"",
how_to_step_1_headline:"",
how_to_step_1_paragraph:"",
how_to_step_2_headline:"",
how_to_step_2_paragraph:"",
how_to_step_3_headline:"",
how_to_step_3_paragraph:"",
how_to_step_4_headline:"",
how_to_step_4_paragraph:"",
content_block_4_headline:"",
content_block_4_paragraph:"",
content_block_5_headline:"",
bike_description_handle_bar:"",
bike_description_front_wheel:"",
bike_description_title:"",
bike_description_frame_bar:"",
bike_description_seat:"",
bike_description_lock:"GPS Enabled, mobile synced, smart lock. ",
bike_description_brake:"",
bike_description_back_wheel:"",
bike_description_kcikstand:"",
content_block_6_headline:"",
call_to_action_2_button_text:"",
:"",
country: country
)
page.save
