country = Country.find_by(country_code: 'US') ? Country.find_by(country_code: 'US') : Country.create(name:'United States', country_code:'US')
page = RidersPage.new(
page_title:"Riders",
content_block_1_headline:"choose a better bikeshare",
content_block_1_paragraph:"With ofo, you pick up a bike, get where you're going, and leave it there. No docking stations, no walking the rest of the way. Because that's what a bike share is supposed to be.",
content_block_2_headline:"grab a bike anywhere. park a bike anywhere.",
content_block_2_paragraph:"With station-free bike sharing, you can ride wherever you please. All you have to do is park your bike legally.",
call_to_action_1_headline:"start riding ofo today",
call_to_action_1_button_text:"Download on",
content_block_3_headline:"riding ofo couldn't be easier",
content_block_3_paragraph:"Find it. Scan it. Ride it. Lock it.",
how_to_step_1_headline:"find a bike",
how_to_step_1_paragraph:"Open the app and find all the bikes around you.",
how_to_step_2_headline:"tap and scan",
how_to_step_2_paragraph:"When you’re at the bike, tap the “unlock” button and scan the barcode to automatically unlock the bike.",
how_to_step_3_headline:"enjoy the ride",
how_to_step_3_paragraph:"Explore your city and arrive at your destination safely",
how_to_step_4_headline:"park and lock",
how_to_step_4_paragraph:"At your destination, simply park your bike safely and legally, and manually lock it to automatically end the trip.",
content_block_4_headline:"the best deal around",
content_block_4_paragraph:"only $1/hour",
content_block_5_headline:"you're safe with us",
bike_description_handle_bar:"Unique bicycle identification number",
bike_description_front_wheel:"LED Dynamo Headlight – visible from 500ft",
bike_description_tire:"Solid tire that never deflates",
bike_description_frame_bar:"Strong durable and light aluminum body",
bike_description_seat:"Adjustable seat to accommodate user preferences",
bike_description_lock:"GPS Enabled, mobile synced, smart lock. Data can be used to inform transportation planning",
bike_description_brake:"Reliable and easy to use brake",
bike_description_back_wheel:"Red back reflector to alert motorists and pedestrians",
bike_description_kickstand:"Kickstand for upright parking without a docking station",
content_block_6_headline:"Featured in",
call_to_action_2_headline:"start riding ofo today",
call_to_action_2_button_text:"Download on",
country: country
)
page.save
